export const USER_ROUTES = {
  HOME: '/user/home',
  PROFILE: '/user/profile',
  CHANGE_PASSWORD: '/user/change-password',
  EXPLORE: '/user/explore',
  EVENT_DETAILS: '/user/event/:id',
  BOOKINGS: '/user/bookings',
  MY_TICKETS: '/user/my-tickets',
  CHECKOUT: '/user/checkout',
  PAYMENT_STATUS: '/user/payment-status',
  TICKET_VIEW: '/user/booking/:id',
  WALLET: '/user/wallet',
  ORGANIZER_PROFILE: '/user/organizer/:id',
  PAST_EVENT_DETAILS: '/user/organizer/past-event/:id',
  SETTINGS: '/user/settings',
  SUPPORT: '/user/support',
  HELP: '/user/help',
  ABOUT: '/about',
};
